# Controls when the action will run. Triggers the workflow on push or pull request
on: [push, pull_request]

defaults:
  run:
    working-directory: ./


jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      working-directory: webapp/
      - uses: actions/checkout@v2
      - name: Linting frontend with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing â¬
        run: yarn install
      - name: Run lint ğŸ§ª
        run: yarn lint

  test-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      working-directory: webapp/
      - uses: actions/checkout@v2
      - name: Testing frontend with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing â¬
        run: yarn install
      - name: Run tests ğŸ§ª
        run: yarn test:unit

  lint-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    working-directory: backend/
      - uses: actions/checkout@v2
      - name: Linting backend 
      - name: Installing â¬
        run: yarn install
      - name: Run lint ğŸ§ª
        run: yarn lint

  # test-backend:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [14.x]
    
  #   steps:
  #    working-directory: backend/
  #     - uses: actions/checkout@v2
  #     - name: Testing backend 
  #     - name: Installing â¬
  #       run: yarn install
  #     - name: Run tests ğŸ§ª
  #       run: yarn test


